# Generated by Django 5.2.1 on 2025-07-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=False)),
                ('lastname', models.CharField(max_length=30, null=False)),
                ('email', models.EmailField(max_length=254, unique=True, null=False)),
                ('password', models.CharField(max_length=128, null=False)),
                ('edad', models.IntegerField(null=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
